
[package]
name = "ccpp-monitor"
version = "0.1.0"
description = "Industrial Monitoring for CCPP"
authors = ["Firebase Studio"]
license = ""
repository = "https://github.com/ahmedyoussef-b/centraleconnect.git"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "shell-open" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10.8"
ably = "0.2.0"
opcua = { version = "0.11.0", default-features = false, features = ["rustls-client"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
rand = "0.8"
tokio-stream = "0.1"
rusqlite = "0.31.0"
sqlx = { version = "0.7", features = [ "runtime-tokio-rustls", "postgres", "chrono" ] }


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

