@[package]
name = "ccpp-monitor"
version = "0.1.0"
description = "Industrial Monitoring for CCPP"
authors = ["Firebase Studio"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "shell-open", "microphone" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri-plugin-sql = { version = "~1.3.0", features = ["sqlite"] }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10.8"
ably = "0.2.1"
opcua = { version = "0.11.0", default-features = false, features = ["rustls-client"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
rand = "0.8"
tokio-stream = "0.1"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
