
[package]
name = "ccpp-monitor"
version = "0.1.0"
description = "Industrial Monitoring for CCPP"
authors = ["Firebase Studio"]
license = ""
repository = "https://github.com/ahmedyoussef-b/centraleconnect.git"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.6", features = [] }

[dependencies]
tauri = { version = "1.6", features = [ "window-set-cursor-icon", "window-set-fullscreen", "dialog-save", "fs-create-dir", "window-set-ignore-cursor-events", "window-set-decorations", "window-set-always-on-top", "window-set-min-size", "fs-rename-file", "window-start-dragging", "window-set-title", "window-set-focus", "window-request-user-attention", "fs-read-file", "fs-write-file", "fs-remove-dir", "fs-copy-file", "window-center", "window-set-cursor-visible", "fs-remove-file", "window-set-position", "window-set-cursor-grab", "dialog-open", "window-create", "window-set-size", "window-set-max-size", "fs-read-dir", "window-set-cursor-position", "shell-open" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10.8"
ably = "0.2.0"
opcua = { version = "0.11.0", default-features = false, features = ["rustls-client"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
rand = "0.8"
tokio-stream = "0.1"
rusqlite = "0.31.0"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

